theme: jekyll-theme-tactile

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "License.md"]
highlighter: rouge


title : Home
author :
  name : Hangjian Li
  email : lihangjian123@ucla.edu
  github : hangjianli
  twitter : Hangjian Li

production_url : https://hangjianli.github.io
BASE_PATH : https://hangjianli.github.io
