theme: jekyll-theme-tactile

exclude: [".rvmrc", ".rbenv-version", "ReadMe.md", "Rakefile", "changelog.md", "License.md"]
highlighter: rouge


title : Hangjian Li
author :
#  name : Karl Broman
  email : lihangjian123@ucla.edu
  github : hangjianli
  twitter : Hangjian Li
